name: patientapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.4
  email_validator: ^2.1.17
  # flutter_html: ^2.2.1
  url_launcher: ^6.1.6
  badges: ^3.1.1
  intl: ^0.18.1
  image_picker: ^0.8.5+3
  package_info_plus: ^3.0.1
  package_info_plus_web: ^2.0.0
  path: ^1.8.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  date_picker_timeline: ^1.2.3
  flutter_phone_direct_caller: ^2.1.1
  awesome_drawer_bar: ^1.0.0
  webview_flutter: ^2.0.4
  provider: ^6.0.4
  screen_loader: ^4.0.1
  progress_dialog_null_safe: ^1.0.7
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  dio_logger: ^4.0.8+8
  flutter_math_fork: ^0.7.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/
